name: Process CSV files 2

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the main branch

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python for the workflow
        with:
          python-version: '3.9'  # Specify the Python version, e.g., 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install pandas requests beautifulsoup4  # Install dependencies directly

      - name: Run Python script
        run: |
          python your-python-scripts/your-script.py  # Run the script

      - name: Upload processed CSV files
        uses: actions/upload-artifact@v3  # Upload artifacts
        with:
          name: processed-files  # Name of the artifact
          path: ./output_files/  # Path to the folder containing output CSVs
